- .jscsrc
- .jshintignore
- CHANGELOG.md
- bower.json
- index.js
- karma.conf.js
- package.json
- spec/waypoint_spec.js
- src/waypoint.js
- webpack.conf.js
Reverts brigade/react-waypoint#12
I'm getting errors publishing the new version to npm - want to investigate more.
> Revert "Setting up npm build"

- CHANGELOG.md
- build/npm/waypoint.js
- package.json
- spec/waypoint_spec.js
- src/waypoint.jsx
Upgraded to work with [React 0.14](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html).
All tests :seedling: for me.
> Upgrade for React 0.14

- CHANGELOG.md
- README.md
- build/npm/waypoint.js
- spec/waypoint_spec.js
- src/waypoint.jsx
This adds 4 more optional properties to the Waypoint component: `onEnterFromAbove`, `onEnterFromBelow`, `onLeaveToAbove`, `onLeaveToBelow`.
I haven't updated any tests yet, so don't merge this yet. I just want to make sure this is something that could be accepted before I put too much time into it :)
> Add direction specific functions

- package.json
Related to: https://github.com/brigade/react-waypoint/issues/74
> Add React 15.0 support

- README.md
- package.json
- spec/waypoint_spec.js
- src/waypoint.jsx
> propose `throttleHandler' prop

- .eslintrc.js
- package.json
- src/waypoint.jsx
> update linter and npm scripts

- README.md
I'm using this library to implement [scrollspying](http://v4-alpha.getbootstrap.com/components/scrollspy/), so I thought it might be good to call it out in the README. Perhaps surprisingly, this library is by far the best lib I've found to implement Scrollspies (even better than React scrollspy-specific libraries, imo), which is why I think it's a good idea to mention it in the README.
NBD if you don't think it's a good example, though :)
> Add scrollspy as example for how this lib can be used

- spec/waypoint_spec.js
- src/waypoint.jsx
I was using this component and I ran into what I thought might be a bug. I didn't see any tests that demonstrated what I was looking for, so I did some refactoring to make this more obvious and robust. It turned out that I was using the prop incorrectly, but I thought that the refactoring was still worthwhile.
> Minor refactoring

- package.json
- src/waypoint.jsx
I want to use the event handling code that I wrote for react-waypoint in
some different projects, so I decided to extract it to its own package,
generalize it some, and write some tests. This commit completes the
extraction by removing the code from react-waypoint, adding the
dependency, and updating the usage to match the new API.
https://github.com/lencioni/consolidated-events
> Extract event handling code to separate package

- INTHEWILD.md
Successfully using both vertical _and_ horizontal scrolling (on mobile) in production for [Yorango's Listings marketplace](https://www.yorango.com/listings) :)
> add Yorango to INTHEWILD.md

- INTHEWILD.md
We've been using Waypoint for awhile now. It's been awesome! :v:
> Add Netflix org to INTHEWILD.md

- package.json
- spec/waypoint_spec.js
- src/waypoint.jsx
With React 16 soon to be released, I'm going through a process to
prepare the codebase for that version.
> React 15.5

- .travis.yml
To quote @trotzig in https://github.com/brigade/react-waypoint/pull/172#discussion_r110601306:
> One issue though is that we're not really testing with react 14. So if things go south, we'll likely find out about it from an issue.
This PR makes it so that Travis will be the one to let us know.
> Test React 14 in Travis

- .travis.yml
- package.json
- src/waypoint.jsx
- test/waypoint_test.jsx
Will resolve #213 
---
Note: Travis CI will fail because React 16 isn't out yet. But, once it is out, we can restart the build and this _should_ work.
Also, we can close this PR out and just keep the branch around if we don't want to wait to have this PR hanging around. But it sounds like 16 should be released soon.
> Update to support React 16

- README.md
Forgot to remove this in my previous PR #234
> Remove a note about using react-waypoint/es

- INTHEWILD.md
❤️for the component. It worked beautifully! ✨
> Adding Matter to the list in the wild

- .travis.yml
- package.json
- src/waypoint.jsx
Since I'm proposing a few breaking changes might as well throw this one in. The effect is absolutely tiny but this is as good a time as any to do it.
> [Breaking] Require React 15.3 and simplify some code

- README.md
- index.d.ts
- src/waypoint.jsx
- test/performance-test.jsx
- test/waypoint_test.jsx
> [Breaking] Make Waypoint a named export.

- src/waypoint.jsx
> Fix isForwardRef call

- .babelrc
- package.json
Babel update handled via `npx babel-upgrade --write`.
> Update babel 6 → 7, rollup 0 → 1

- .babelrc
This is low risk here and should improve the performance of this
code.
More information:
- https://github.com/airbnb/babel-preset-airbnb#classes-loose-mode
- https://babeljs.io/docs/en/babel-plugin-transform-classes#loose
es/index.js diff
```diff
1,4c1
< import _classCallCheck from '@babel/runtime/helpers/esm/classCallCheck';
< import _createClass from '@babel/runtime/helpers/esm/createClass';
< import _inherits from '@babel/runtime/helpers/esm/inherits';
< import _createSuper from '@babel/runtime/helpers/esm/createSuper';
---
> import _inheritsLoose from '@babel/runtime/helpers/esm/inheritsLoose';
221,223c218
<   _inherits(Waypoint, _React$PureComponent);
< 
<   var _super = _createSuper(Waypoint);
---
>   _inheritsLoose(Waypoint, _React$PureComponent);
228,230c223
< …
```
> Compile classes in loose mode
