spec/waypoint_spec.js
src/waypoint.js

We introduced a bug in d5eb92bc0149bf which caused Waypoints that listen
to scroll events on the `window` object to fail. This was because we
switched from parentNode to parentElement when traversing up the DOM
tree. This in turn meant that on the way to `window`, we would now pass
the `document` node. This node has no styles, and if you try calling
`window.getComputedStyles` on it, it will return `null`.
I've added a guard for this scenario that will bring back the desired
behavior.
While adding a spec, I noticed that a previous, seemingly unrelated,
spec was suddenly failing. It was meant to test the fact that we
explicitly throw an error if the offsetParent for the Waypoint node does
not have positioning. This is done to help prevent unexpected behavior
when using the Waypoint …

Fix window scrolling

---

README.md
index.html
src/waypoint.js
styles/examples/basic.css
styles/examples/examples.css
styles/examples/infinite-scroll.css
styles/site.css

- Replaces the JSFiddle basic example with a live inline demo and sample code
- Adds a live inline demo of infinite scroll
The infinite scroll demo can be referenced in an upcoming blog post/tutorial about React-Waypoint.
Notice that this pull request is to be merged with the 'gh-pages' branch, and will update the Github Pages site for this project.

Adding examples to gh pages

---

CHANGELOG.md
src/waypoint.js

(From the relevant issue:)
We listen to the 'scroll' and 'resize' events on the 'scrollableParent'
element, which is sometimes the window. However, the 'resize' event is
[only triggered on the window element][mdn-resize-event], so we may not
catch it in cases that the 'scrollableParent' is not the window.
It seems safer to listen to the 'resize' event always on the window,
rather than the scrollable parent.
[mdn-resize-event]: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onresize

Listen to 'resize' on window, not scrollableParent; fixes #8

---

index.html
styles/examples/examples.css

We want our examples to be bookmarkable, so this component adds
bookmarkable headers in the style of Wikipedia.
It would be nice if all our headers in the documentation were
bookmarkable - resusing the BookmarkableHeader component there would be
easy if the whole content of the page were rendered by React.
We may be re-organizing the project to use the build system, and if we
do that on the github pages branch then we can more easily split the
inline scripts into separate files. Rendering the whole page content as
a React component will follow naturally from that step. (See issue #7)

Use BookmarkableHeader component in examples; fixes #6

---

src/waypoint.jsx

`_handleScroll` is dispatched by scroll and resize events as well as React lifecycle events. In addition, `onEnter` and `onLeave` should be `call`ed with the context of the parent element being scrolled. These handlers aren't automatically bound to the component with ES6-based React classes, and even for ordinary `React.createClass` components, the handler would be bound to the parent element which is not necessarily the scrollable parent element that Waypoint identifies. It's useful to be able to distinguish between the events and determine the scrolling component, and this change adds no overhead or complexity.

Add event and context

---

CHANGELOG.md
package.json

This will allow people to use react-waypoint with the 0.14.0 beta
version of React, which might be useful if you want to currently depend
on other things that require the latest beta version of React, such as
Relay.
Fixes #21

Allow React 0.14.0-beta peerDependency

---

spec/waypoint_spec.js

We've had reports of onEnter firing multiple times while in view
(e.g. #28). I've been trying to reproduce the bug with a test, but I
can't reproduce it. I'm adding the test that I wrote anyway as it will
prevent possible regressions. It might also inspire someone else to dig
in and find other things that I didn't find.

Add test to verify that onEnter is called only once

---

README.md

At Brigade, we recently bumped into an issue where <Waypoint> would
always call `onEnter` no matter if it was visible or not. We determined
that this was due to a change we made that caused its scrollable
container to have a height that was both larger than the window's
viewport height and so that the container did not actually scroll (it's
overflow was still set, but it's height was tall enough for whatever
content it received). We brainstormed some ideas for how to resolve this
in react-waypoint, but the we are worried about the performance
implications of the solutions. We believe that this may be enough of an
edge case that we don't actually need to solve right now, so we decided
to document this in the readme to help others who might be running into
this issue. If this becomes more …

Document some limitations in the readme

---

spec/waypoint_spec.js
src/waypoint.jsx

The `<html>` tag itself is not scrollable, it causes the window to scroll.

Skip `<html>` when looking for scrollable ancestor

---

spec/waypoint_spec.js
src/waypoint.jsx

If your onEnter/onLeave callback made the `<Waypoint>` re-render, you
could end up with duplicate callback calls. This was because we were
remembering the previous position too late. Consider the following
example:
```
<List>
{items.map((item) => <Item item={item}/>)}
<Waypoint onEnter={() => this.setState({ foo: 'bar' })}/>
</List>
```
When the waypoint is in view, it will fire the onEnter callback. The
setState call will then make the waypoint update/re-render. Since we are
checking waypoint position inside componentDidUpdate, we call onEnter
again.
I thought about adding one or a few defers here and there to fix this
problem (setTimeout(this._handleScroll)), but I ran into a few problems
with getting all specs to pass. Also, I'm a little bit afraid to break
some implementations that …

Fix double fire

---

CHANGELOG.md
README.md
spec/waypoint_spec.js
src/waypoint.jsx

Now that these strings are being passed as arguments to `onEnter` and
`onLeave`, I think it makes sense to expose them as statics so that
others can feel more confident about using them.

Expose 'above' and 'below' as statics

---

CHANGELOG.md
src/waypoint.jsx

In the Brigade app, we've seen an error occasionally happen in
production where `this === null` inside of the `_currentPosition`
function. This causes `ReactDOM.findDOMNode` to error out.
While I'm not entirely sure I understand how this could happen, my
hypothesis is that the component has become unmounted before the scroll
handler can be executed, causing a race condition. Ensuring that the
component is mounted before executing the handler should prevent this
from happening.

Ensure component is mounted when executing scroll handler

---

build/npm/waypoint.js
package.json
spec/waypoint_spec.js
src/waypoint.jsx

Because offsetTop doesn't take that into account. Instead I used node.getBoundingClientRect with some adjustments, based on jQuery:
https://github.com/jquery/jquery/blob/29370190605ed5ddf5d0371c6ad886a4a4b5e0f9/src/offset.js#L110
This also has the advantage that if window is the scroll container, we get the result immediately (instead of using recursion) which might be slightly faster.

Calculate proper offset when <html> or <body> has a margin

---

src/waypoint.jsx

The method signature was changed a while ago to instead return a string.

Fix out-of-sync comment for `_currentPosition()`

---

.babelrc
package.json

With Babel 6, the default export behavior changed [1] so that there's no
longer a `module.exports = ...`. This causes problems down the line,
because other projects that depend on react-waypoint will need to import
it through
const Waypoint = reauire('react-waypoint').default;
(notice the added `.default`)
Thankfully, there's a plugin that will automatically inject the
`module.exports` for us [2]. I've added and configured that plugin in
this commit.
[1]: https://phabricator.babeljs.io/T2212
[2]: https://www.npmjs.com/package/babel-plugin-add-module-exports

Make bundled waypoint.js easier to import

---

.gitignore
README.md
package.json
src/waypoint.jsx

The new Prop is to allow the developers to disable firing of onEnter/onLeave events on rapid scrolling.

New prop added - fireOnRapidScroll

---

src/waypoint.jsx

When `scrollableParent` prop is set to a DOM element, waypoint writes a warning `Warning: Failed propType: Invalid prop scrollableParent supplied to Waypoint, expected a ReactNode.` to the browser console
This is a fix for that warning according to what README says about `scrollableParent` prop type

scrollableParent prop type fix

---

CHANGELOG.md
README.md
spec/waypoint_spec.js
src/waypoint.jsx

The PR that added this prop type was based on code that named the
scrollable element used to determine visibility "scrollableParent".
Since then, we've changed the name to the more general one (f98f7dc).
Renaming the prop helps keep the code consistent.

Rename `scrollableParent` prop to `scrollableAncestor`

---

spec/waypoint_spec.js
src/waypoint.jsx

This can happen for a variety of reasons, e.g. a transition animation.
Rather than throwing an exception, we set the position to the new "invisible"
position. When the component becomes visible and we notice in the next scroll
event (or forced update), and standard event handlers will fire as we notice
the change from "invisible" to whatever the new state is.

Handle waypoint parent not being visible

---

README.md
spec/waypoint_spec.js
src/waypoint.jsx

While I'm doing some stuff in this codebase, here's another thing that would make life a bit easier for us.
When a waypoint's position has changed, we often just want to know what the new position is. Currently we have to write both `onEnter` and `onLeave` handlers to convert this info back into a single position update, but since the Waypoint internally already has this as a single position change, it seems like this is an easy and useful thing to expose.
While the existing events pass (event, new/old position) as the params, I consciously decided not to follow the convention and passed (new position, old position, event) in that order, since the most frequent use case is just wanting to know the new position, so it's a pain to have to write handlers that take an event as the first param …

Add onPositionChange event

---

src/waypoint.jsx

Setting `displayName` ensures that developers can search for <Waypoint> components more easily in the Chrome Developer Tools React extension.

Add displayName for easier debugging

---

spec/waypoint_spec.js
src/waypoint.jsx

This is a pretty clean refactor. Only 1 test had to be modified (that one does bother me, though. See my note, below).
Here's why we did the refactor...
We have a component, `<StickyHeadingList>`, (https://gist.github.com/kmayer/8f1ea347cf688b0bc0f866856ec9aedc) which uses the following format:
```html
<StickyHeadingList>
<section class="sticky-section">
<header>Sticky-ish header</header>
<div>content</div>
<div>content</div>
...
</section>
<section class="sticky-section">
<header>Next sticky-ish header</header>
<div>more content</div>
<div>more content</div>
...
</section>
</StickyHeadingList>
```
in the component, this gets mapped to:
```jsx
<div className="sticky-heading-list">
<article ref="stickyList" className="sticky-list-wrapper" onScroll={this.handleScroll}>
{this.props.children} …
```

Refactor _currentPosition to use getBoundingClientRect()

---

README.md

`npm link` command include `npm run build-npm`.  `babel src/waypoint.jsx --out-file build/npm/waypoint.js` step is not needed.
Add `npm run build-npm` advice is rebuild needed. Is not better `npm` cli than per project build syntax like `babel src/waypoint.jsx --out-file build/npm/waypoint.js`?

update README Troubleshooting

---

package.json

On windows 
* we don´t have `rm -fr`
* `mkdir` fail with path.
* `./node_modules/.bin` npm tool  by default add it to path

fix for development on windows

---

package.json

The `prepublish` script has a bad name, I think, 'cause most people use it for things they only want to run right before publishing to npm, yet the script also runs on `npm install`. It looks like this lib only intends for it to be run before publish (correct me if I'm wrong!), so this PR adds the [`in-publish`](https://github.com/iarna/in-publish) lib to filter how frequently the task is run.

Use in-publish to ensure prepublish is only run at right time

---

README.md

current ` throttleHandler: PropTypes.func,` comment is little confuse on README.
Good catch!! on `throttle.cancel` Thanks for add it.

fix a typo and description on README

---

spec/waypoint_spec.js
src/waypoint.jsx

This is a WIP to resolve https://github.com/brigade/react-waypoint/issues/77
It has two notable changes:
1. `threshold` has been split into `offsetTop` and `offsetBottom`
2. The new options accept strings and numbers. Strings can be of the form `"100"`, `"100px"` or `"20%"`. Actual numbers, like `20`, are assumed to be pixel values
---
I haven't added tests 'cause I figure there might be feedback on the implementation. Once the implementation is :+1:'d I'll update the tests.

Replace threshold with topOffset and bottomOffset

---

README.md

In #88, a request was made for demos of how to use these props. I think demos are a great idea! I'd love to see more demos for this library.
This PR doesn't add demos, but what it does add are explanations for why these props are useful, and situations where a developer might use them. I wrote this pretty quick, so go ahead and give lots of feedback. Also, what do you think of the general approach of including text-based guides? Good idea? Bad idea? Is it too verbose? 😛 
I'm just trying to come up with ways to help consumers of the lib. Let me know what you think!

Some guides for offsets and scrollableAncestor

---

src/waypoint.jsx

Not passing props through super() breaks Waypoint usage in [preact](https://github.com/developit/preact).

Passing props from constructor() to super() method

---

src/waypoint.jsx

We've seen this error come up in production:
> Unable to get property 'getBoundingClientRect' of undefined or null
> reference
This boils down to an assumption inside `_getBounds` that we have a
reference to the underlying DOM node (<span>). In some situations, it
looks like we don't. While I don't understand how this can happen
(afaict we clean out scroll listeners properly), returning early will at
least prevent the error from happening.
One theory I had was that the child span (which is what the ref refers
to) is unmounted before the parent. In that case, the ref will be `null`
for a short moment. But that turned out to be an incorrect theory, as
this jsfiddle shows:
https://jsfiddle.net/69z2wepo/56241/
(open the console log to see more info)
Apart from that, I'm currently out of …

Bail early if no ref exists

---

src/waypoint.jsx

In the latest version of React, <Waypoint> is causing a lot of these
warnings to show up in the console log:
application.self-8f8100c….js?body=1:1512
Warning: You are manually calling a React.PropTypes validation function
for the `debug` prop on `Waypoint`. This is deprecated and will not work
in the next major version. You may be seeing this warning due to a
third-party PropTypes library. See
https://fb.me/react-warning-dont-call-proptypes for details.
I think we can avoid this by not assigning propTypes to a variable
before setting them on the React class.

Avoid React warning about propTypes

---

spec/waypoint_spec.js
src/waypoint.jsx

I am looking into improving the performance of react-waypoint. We can be
a little more mindful of how many event listeners we end up creating by
only managing a single event listener. Using Chrome's timeline tool, I
have verified that this type of optimization is significant when there
are a lot of event listeners on the page.
Since we always set up a window resize event, this seemed like a good
place to start for this optimization. I chose a Set, since that seemed
like the easy and nice way to go, but it will require that older
browsers have a polyfill.
If we like this approach, I plan to do something similar for the scroll
event listeners. These are a little more complicated since they could be
attached to any scrollable container, instead of just the window. One
option would be to use …

Manage a single window resize event instead of one per component

---

src/waypoint.jsx

I originally wrote this as a simple object to handle resize event
listeners. I now want to apply the same technique to the scroll event
listeners, but since they are added to different targets, I need to make
my solution a little more generic.
I started by thinking I could use an object of objects to track the
targets and event types and to manage all of the event listeners there.
However, since we need the keys to be references to DOM nodes, that
doesn't work because different DOM nodes of the same type end up being
the same key in an object. I think Map would work here, but if the DOM
nodes are removed before removing the event listeners, we don't have a
great way of cleaning up the Map, so I think we would end up with a
memory leak. WeakMap seems pretty ideal here, but the browser …

Use as few scroll events as possible, and use passive event listeners

---

src/waypoint.jsx

If a waypoint unmounts another waypoint as part of handling an
onEnter/onLeave, and the two waypoints are attached to the same
scrollable ancestor, we could end up with this error:
Uncaught TypeError: handlers[index] is not a function
Consider the following example, where the first handler removes the
second:
```js
const a = {}
a.handlers = {
1: function() {
delete a.handlers[2];
},
2: function() {},
};
Object.keys(a.handlers).forEach(function(index) {
a.handlers[index]();
});
// => Uncaught TypeError: a.handlers[index] is not a function(…)
```
Adding a guard against undefined handlers fixes the problem. Testing
this turned out to be quite hard, so for now I'm just rolling with a
manual fix.
Fixes #126

Check for handler presence before invoking it

---

src/waypoint.jsx

In c6711294 I made a change to waypoint that makes it so it sets up
fewer event listeners. Unfortunately, I did this in a way that causes
the added event listener to never be removed, as @trotzig pointed out at
https://github.com/brigade/react-waypoint/commit/c6711294#commitcomment-19498628
This is happening because every time we call .bind() on a function, we
get a new object, which the browser is unable to use to remove the
previous function. The solution is to bind the function once, and keep
track of it so we can reuse the reference when we want to remove the
event listener.

Avoid leaking event listeners

---

spec/waypoint_spec.js
src/waypoint.jsx

At Airbnb we are using react-waypoint to do some lazy image loading. We
noticed a problem on a page that has three images that are initially
rendered within the viewport and use waypoint to start the image loading
process. Sometimes one or two of the images don't start loading until
after you scroll a little, even if they are initially rendered within
the viewport.
Our hypothesis is that `this._ref` is not ready yet at the time this
function is called, which is guarded against in the handleScroll method.
We believe that by delaying the initial execution of this function, the
browser will have time to wire up the ref and our waypoints will
appropriately trigger when they are initially rendered.
We have tested this out in a development environment, and it seems to
resolve the issue for us. …

Delay initial calling of handleScroll when mounting

---

README.md
spec/waypoint_spec.js
src/waypoint.jsx

Implements #66 
To explain some of my rationale, as I was writing this I quickly realized that little of the internal logic actually needs to change to support horizontal scrolling (approx. 7 lines).
Instead of creating new `POSITIONS` and forking a bunch of functions and creating more variables (e.g. `viewportLeft`, `waypointLeft`, etc), it would actually make more sense to abstract all the code into things like `viewportEdge1`, `contextSize`, `contextScrollEdge1`, `POSITIONS.outside1`, `POSITIONS.outside2`, but as I started renaming everything, I realized that would be a major breaking API change.
Ideally, I think there should be some internal implementation like that, and then a wrapper component can just convert props like `bottomOffset` or `leftOffset` to `edge1Offset`, but for now, …

Add horizontal scrolling

---

.npmrc
CONTRIBUTING.md
package.json

I recently added a few npm scripts to help making the release process go
smoother. Unfortunately, they caused a little bit of confusion because
some folks were still trying to use the built-in `npm version` command
instead of the new `npm run version:foo` scripts.
I poked around npm documentation a bit and discovered that we can set
things up so that `npm version` does what we want. The magic is done by
moving the command flag to avoid the automatic creation of the git tag
out of the script and into a .npmrc file.
The result of this is now `npm version major|minor|patch` will manage
the full release process for you.
To: @trotzig @ljharb

Improve publishing process

---

CHANGELOG.md
README.md
package.json
spec/waypoint_spec.js
src/waypoint.jsx

This prop has had people confused. It was added to allow people to
better control scrolling performance in their applications. Since we
added it, we've done other changes to improve performance (3ad940e,
c67112) which has made the benefit of throttling questionable. Removing
it will reduce the complexity of the component.

Remove support for throttleHandler prop

---

index.d.ts
package.json

Hi there, this pull request adds the typescript 2 type definitions to your module.
I used your documentation to create the file and followed [those guidelines](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).
I'm just wondering about wether or not have a dependency on @types/react.
Let me know if you need anything fixed :smile_cat:

add typescript types definition file

---

index.d.ts

@nicolas-schmitt, this type definition assumes the module is a CommonJS/AMD module rather than an ES6 one, which forces us to import the module like so if we're using TypeScript:
`import Waypoint = require('react-waypoint')`
But react-waypoint seems like it's an ES6 module with a default export, so in theory, this should work:
`import Waypoint from 'react-waypoint'`
However, the type definition would need to indicate this. By adding a `default` attribute to the type definition, this would allow both styles of imports to work.

Update type definition to support ES6 default imports

---

index.d.ts

@nicolas-schmitt @trotzig, can we revert the prior PR?
I misinterpreted how the build process works. Although the react-waypoint source is written as an ES6 module, because of the add-module-exports module, Babel transforms it into a CommonJS module (and only a CommonJS module -- there is no default export value in the actual build). Therefore, it cannot be imported as a pure ES6 module (import Waypoint from 'react-waypoint' does not work -- it will be undefined), and the original ES6 source file is not included by NPM when published.
I'm not sure if there's a way to publish an NPM module with both ES6 and CommonJS variants, but since that's probably a more involved discussion than a one-line fix to the type definition, I think it makes sense to revert for now.
Apologies for the …

Reverts #147

---

src/waypoint.jsx

There may be some cases where waypoint mounts and then unmounts before
this timeout has an opportunity to happen. For these cases we want to
clear the timeout when the component unmounts to avoid any possible
errors.

Clear timeout when unmounting

---

README.md
spec/waypoint_spec.js
src/waypoint.jsx

Addresses #112 
Intended to supersede #41 
If you pass children to a Waypoint element, `onEnter` will be triggered when the element is fully or partially within the viewport, or if it fully encloses the viewpoint. `onLeave` will be triggered when no part of the element is within the viewport. 
This does not differentiate between full, partial, or enclosing visibility. That would likely require API changes (eg; a parameter being passed to `onEnter` and `onLeave`, new callbacks like `onPartialEnter`, or a new callback with a parameter, eg `onChange(visibility: Enum<'full'|'partial'|'enclosing'|'none'>`). Leaving as a TODO. 
I haven't added tests yet, so this isn't ready to merge. In the meantime, though, here's a screencast:

Accept children

---

README.md

Since scss-lint is basically in maintenance mode, it
doesn't seem right to direct people in that direction
anymore.
https://github.com/brigade/scss-lint/commit/4ac76f95

Remove scss-lint link from readme

---

src/waypoint.jsx

Using the same technique that React uses, we can avoid having these
lines shipped in production. This is unlikely to make much of a
difference, but since it is simple enough it seems like an easy, tiny
win.

Minify out debug code in production build

---

spec/waypoint_spec.js

I was thinking about making a change to waypoint, but I found the tests
to be unnecessarily difficult to follow, so I decided to first reduce
some of the indirection and nesting. I think there is more that could be
done here, but this seems like a pretty good start.

Remove some unnecessary indirection in tests

---

README.md
spec/resolveScrollableAncestorProp_spec.js
src/computeOffsetPixels.js
src/constants.js
src/debugLog.js
src/ensureChildrenIsSingleDOMElement.js
src/getCurrentPosition.js
src/isDOMElement.js
src/parseOffsetAsPercentage.js
src/parseOffsetAsPixels.js
src/resolveScrollableAncestorProp.js
src/waypoint.jsx

When Waypoint is rendered on the server, `window` is not available.
To make Waypoint easier to work with, we allow this to be specified in
string form and safely convert to `window` here.
While I was at it, I also broke out a bunch of functions into their own
modules to make it easier to work with this project and to eventually
improve our testing story. This is probably best reviewed
commit-by-commit.
semver minor

Teach scrollableAncestor prop to take "window" as a string

---

src/waypoint.jsx

I was doing some profiling and noticed a pattern on pages that have a
lot of waypoints. In the timeline I can see that we spend a non-trivial
amount of time in clearTimeout (~0.25ms per waypoint on my laptop). This
can add up, so let's avoid the extra work by adding a check.

Avoid unnecessary clearTimeout when unmounting

---

CHANGELOG.md
package.json
src/waypoint.jsx

Rather than revert the 4 commits in #172 (most of which are changes that we _do_ want), I just undid the part that was breaking peoples' builds.
Let me know how this looks, and I'll merge and release. Working on the 6.0.0 branch now (which will just `revert` fca1ebb )
Resolves #174

Remove prop-types peerDep; 5.3.1 release

---

README.md

_Forever ago_ in #108, I drew up some images to show how the offsets and boundaries work. @trotzig recommended I add them to the README, and well, I intended to but never did. Whoops.
This finally adds them. There are probably improvements that could be made, but maybe this is a good place to start. What do y'all think?
//cc @xeophin

Add offset and boundary images to the README

---

package.json

Depending on how broken the `prop-types` lib is in `< 0.14.9`, I could see this going out as either a major release, or a bug fix. Because they had to cut a new React version, my guess is that it's probably pretty broken, so I could see it going out as a bug fix.
Has anyone experienced using `prop-types` in `< 0.14.9`?
---
Resolves #179

Restrict lower bound of React to v0.14.9

---

package.json

This resolves some of the discussion in #179. The prop-types package is
small enough to not worry about duplicates ending up in peoples
(webpack/browserify) bundles. Also, other projects are also taking the
same ease-of-installation+dupes-don't-matter approach:
- React Router
https://github.com/ReactTraining/react-router/blob/ed6f3de4ea8baf950e65fd35e6785e0b493fb9e6/packages/react-router/package.json#L44
- Redux-form
https://github.com/erikras/redux-form/blob/4e7f5cfe5f34d2cf02cca841366d58196d330e35/package.json#L64

Move prop-types to a proper dependency

---

spec/waypoint_spec.js
src/waypoint.jsx

We've seen reports (e.g. [1], [2]) where people have to add
`scrollableAncestor={window}`, because their <body> element has an
overflow style that is either "auto" or "scroll". Unless I'm mistaken,
there's no way to make the body scroll independently, which means that
we can assume that the element to attach scroll listeners to is
`window`.
Making this assumption led to a bit of simplification around a few
exceptions we had made when traversing up the DOM tree. Once we reach
`document.body`, we simply return. I can't think of a scenario where we
would want to continue traversing from that node.
[1] #171
[2] #182

Assume `window` as scrollableAncestor for <body>

---

spec/waypoint_spec.js
src/onNextTick.js
src/waypoint.jsx

While doing some profiling, I noticed that on pages that render a lot of
waypoints, a lot of time is spent in componentDidMount. This is mostly
due to the cost of calling setTimeout, but also because of the other
work we are doing in here, like findScrollableAncestor.
By consolidating the setTimout calls, we greatly reduce the cost of
componentDidMount. We can take this a step further and defer
initializing the event listeners and finding the scrollable ancestors
since we won't need any of that anyway until our initial handleScroll
call can happen. This effectively makes componentDidMount free, which
frees up the main thread for more important work, like rendering pixels.
I believe that this also allows the calls to findScrollableAncestor to
work faster by avoiding some layout thrashing. …

Improve startup time

---

src/waypoint.jsx

After trying out v7.0.1, I spotted an error that would happen if the
waypoint was updated before it had a chance to initialize. Since we call
handleScroll when the component updates, which calls getBounds, which
then tries to access the offsetHeight on this.scrollableAncestor, we
expect that this.scrollableAncestor has been defined. But, if the
component updates before the deferred initialization has run, then this
is undefined and we get an error.
I don't have time to write a test for this just now, but I've tried it
out in my app and it fixes the issue so I want to get it released before
much longer.

Fix bug if waypoint updates before being initialized

---

src/onNextTick.js

The PR [Improve startup time](https://github.com/brigade/react-waypoint/pull/188) has introduced a function named `onNextTick` for performance reason to invoke the callback in a batch way. However, it also introduces a bug there.
The basic logic is:
- When the queue being consumed, it will shift its items one by one.
- When the component will unmount, it will unregister from the queue.
The problem is when step2 will wrongly remove something after step 1 gets finished.
```
if (!isSubscribed) { // this guard value doesn't work
return;
}
isSubscribed = false;
const index = timeoutQueue.indexOf(cb); // the index could get -1
timeoutQueue.splice(index, 1);  // almost remove everything from the queue
```
How to reproduce?
- register [cb1, cb2, cb3]
- consume cb1, cb2, cb3
- register [cb4, cb5, …

fix onNextTick

---

spec/onNextTick_spec.js
src/onNextTick.js

We recently had a bug in this function that we fixed in #190, so I wrote
some tests to prevent it from regressing. At the same time I decided to
add an optimization to avoid the array scan after the first time
unsubscribe is called.
cc @ssnau

Add tests for onNextTick()

---

package.json
src/waypoint.jsx

This new version has a slightly simpler API, where addEventListener
returns an unsubscribe function instead of a handle. removeEventListener
has been deprecated.

Update for consolidated-events 1.1.0

---

package.json

So that npm searches for "react scrollspy" bring up this package
---
This is a small change, but it could help more folks find this project

Add "scrollspy" keyword to package.json

---

.travis.yml

This will help us make sure that react-waypoint continues to work for
folks running newer versions of node.

Add node 7 and 8 to Travis CI test matrix

---

.babelrc
package.json
rollup.config.js

Previously, we were building waypoint just by running it through Babel.
Since we split things out into separate modules, this caused a bit of
extra overhead in the bundle size and at runtime due to the extra
wrapping of these modules.
Thankfully, rollup was built to help us produce a smaller build. To make
this work, I needed to remove the Babel configuration that specifies a
module transformer, so I decided to switch to the Airbnb Babel preset,
which exposes an option for this (and under the hood uses
babel-preset-env, which we need to migrate to anyway). More info:
https://github.com/rollup/rollup-plugin-babel#configuring-babel
The rest of this was loosely based off the rollup-starter-lib
configuration. This gives us an ESM build pretty much for free. …

Build with rollup

---

test/waypoint_test.jsx

Fixing the test that was disabled due to the React 16 error boundaries handling: https://github.com/brigade/react-waypoint/pull/215#issuecomment-333627647
I found out that with error boundaries, error throws twice in development mode, here is a justification for that from React team: https://github.com/facebook/react/issues/10384#issuecomment-334142138
I found a fix for that although it looks a little hacky. The other option could be to run tests in `production` mode, but that breaks debug tests and I'm not sure how to fix this.

Fix test failing because of react error boundaries

---

.eslintignore
.gitignore
README.md
package.json
rollup.config.js

After releasing 7.3.0, we've seen folks run into issues (#221) with the
new `module` field added to package.json. I've tried to read up on how
webpack uses this field, and it looks like it will pick it up by
default. This is tricky because most people will expect a CommonJS
export (i.e. `module.exports = ...`), but now they suddenly have to
import react-waypoints using
const Waypoint = require('react-waypoint').default;
There's a lengthy issue over at webpack discussing this [1], with a few
proposed solutions at the bottom:
- offer a separate package like lodash does (lodash-es), or
- skip the module field and use a es-specific entry point, like import a from 'yourpkg/es'
- skip the module field, avoid es modules (my preferred solution for most of my modules)
I'm opting for the second …

Make ES module opt-in

---

index.d.ts

TS definition was using old style declaration, which was also not exporting the namespace.  Use this as `import * as Waypoint from 'react-waypoint'` and it allows access to everything in the namespace e.g. `CallbackArgs`

Update typescript definition

---

index.d.ts

JSX elements in Typescript require two args when defined, props and state.  This provides a null arg for state, killing the below Typescript errors:
_Happens when the library is required-_
`[at-loader] ./node_modules/react-waypoint/index.d.ts:3:32
TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).`
_Happens when library is used -_ 
`[at-loader] ./src/Components/Publishing/Nav/Nav.tsx:73:10
TS2604: JSX element type 'Waypoint' does not have any construct or call signatures.
`

Add second arg to Typescript component definition

---

package.json
rollup.config.js

Webpack2+ and rollup will understand this out of the box when importing from the lib, no need to import from `'react-waypoint/es'`

Added module entry point in package.json

---

index.d.ts

These properties are set [directly on the constructor](https://github.com/brigade/react-waypoint/blob/master/src/waypoint.jsx#L324-L327), and thus should be static. The current typings cause an error if you attempt to access those properties:
```
Property 'inside' does not exist on type 'typeof Waypoint'.
```

Type Waypoint class properties as static

---

index.d.ts

Fix `export` to es6 syntax in type definition. Used `default export`. If #238 is on purpose, consider this PR
([Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export))

Fix import error in typescript

---

test/waypoint_test.jsx

We have a test that verifies that an error is thrown as part of
rendering a waypoint with more than one child. Even though we take
measures to prevent the error from leaking outside the test itself,
Karma picks it up and prints a confusing log:
ERROR: 'The above error occurred in the <Waypoint> component:
in Waypoint
in div
No error is logged above that line, which makes it hard to understand.
While it's probably possible to get rid of that line some other way, I
opted for a simple solution to begin with, simply logging something that
makes it A) easier to ignore B) easier to find the offending test case.

Add message to better understand log message in tests

---

src/waypoint.jsx

I was doing some profiling and I noticed that when Waypoint updates, we
call `this._handleScroll` synchronously, which eventually calls functions
that force layout. Since this happens during render, the layout is
immediately invalidated and then triggered again once rendering is
completed.
We avoid this problem in `componentDidMount` by deferring this work
until the next tick.
I think we should consider making two changes to Waypoint to help
address this:
1. Extend `React.PureComponent` instead of `React.Component`. In the
place I saw this problem, we were rendering a waypoint with pure
props, so the update in this case could be completely avoided by
using PureComponent.
```jsx
<Waypoint
onEnter={this.onEnterWaypoint}
scrollableAncestor={this.props.scrollableAncestor}
/>
```
2. Defer …

Extend React.PureComponent instead of React.Component

---

.travis.yml

Node 4 is EOL and should not be used anymore. This removes it from the test suite so that we can speed things up a bit.
I've also started explicitly resting React 16, rather than rely on the fact that our devDependencies have React 16.
I've also made explicit testing against at least React 0.14.9, since we don't support versions of React below that, and since it is pre-major version, npm will treat feature versions as major versions.
Further, this also uses the newest version of npm to do our install which should speed things up a bit. npm version is independent of Node version so this should have no impact other than speedier installs.

Stop testing Node 4, explicitly test React versions

---

src/constants.js
src/getCurrentPosition.js
src/waypoint.jsx

If you look at the code after rollup ran, you see that the `constants` object is removed in favour of plain variables. This allows a minifier to shorten them to single letter variables instead of something like `c.inside`.
Since `src/constants.js` is not a published file this is not a breaking change.

Turn the constants into named exports for better minification

---

.babelrc
package.json
src/waypoint.jsx

This will shave a few bytes of every production build. A smart bundler might also notice that `prop-types` is unused and removes that dependency but I wouldn't bet on that.

[Breaking] Remove prop types in production

---

src/waypoint.jsx

Scrollable ancestors can also have `overflow: overlay;`. Currently, react-waypoint does not support that case. This PR adds that support.

Add support for scrollable ancestor with overflow: overlay

---

.travis.yml

It seems to conflicts with the diferent npm versions used in the matrix.
This is because of my change in #322 that always tests on the lasted stable Node.js version and the release of Node.js 7 that bundles npm 7. I think it's good these gets covered in testing but the cache seems to be a problem.

Disable TravisCI's npm cache

---

.travis.yml
package.json

This PR adds testing for React 17 and relaxes the peer dependency constraint on `react` to not warn for React 17
It also updates `react-is` to version 17

Support React 17

---

.babelrc
package.json

This comes with new browser targets:
> Chrome 35 -> 40, Edge 14 -> 18, IE 9 -> 11, Firefox 52 -> 72, Safari 8 -> 12, Android 30 -> 35
It doesn't change the generated code in practice but if some new JS feature gets used that happened to be supported by all of these new targets, they won't get transpiled anymore.

Upgrade babel-preset-airbnb to version 5

---

karma.conf.js
package.json
test/browser/waypoint_test.jsx
webpack.config.performance-test.js

This one was interesting as quite a few things broke when upgrading stuff.
- Karma to version 6 worked as-is.
- `jasmine-core` to 2.99 was a relatively simple change. I believe the test has never worked, jasmine-core 2.7 just exposed that
- On that note, I couldn't figure out how to get up to `jasmine-core` 3
- Webpack 3 just worked but Webpack 4 required some changes as Webpack < 4 didn't correctly execute code in strict mode.
I think most of these changes are no brainers except perhaps the upgrade to webpack. I think it's valuable to test with older webpack versions to assure compatibility. However webpack 4 is now almost 3 years old. I think it's fine to ignore these older versions. Especially since it uncovered tests weren't actually executed in strict mode, potentially hiding bugs.

Upgrade test related dependencies & adapt tests

---

.babelrc
package.json
rollup.config.js

Fixes #302
This is similar to #341, except it avoids having to run babel on the
rollup output, which allows us to leave the babel configuration in
the .babelrc file.
cjs/index.js diff:
```diff
4a5,8
> var _classCallCheck = require('@babel/runtime/helpers/classCallCheck');
> var _createClass = require('@babel/runtime/helpers/createClass');
> var _inherits = require('@babel/runtime/helpers/inherits');
> var _createSuper = require('@babel/runtime/helpers/createSuper');
11a16,19
> var _classCallCheck__default = /*#__PURE__*/_interopDefaultLegacy(_classCallCheck);
> var _createClass__default = /*#__PURE__*/_interopDefaultLegacy(_createClass);
> var _inherits__default = /*#__PURE__*/_interopDefaultLegacy(_inherits);
> var _createSuper__default = /*#__PURE__*/_interopDefaultLegacy(_createSuper); …
```

Use external @babel/runtime helpers

---

README.md
index.d.ts
src/waypoint.jsx

The similarity (or even "specularity") of "topOffset" and "bottomOffset" is kinda obvious, but still does make sense to describe both of them properly (similar to `onEnter` vs `onLeave`)

docs: update "bottomOffset" description

---

index.d.ts

REACT18 TS - Children are no longer  implicit property of a Component.
Children has to now be specified explicitly on the props declaration.

REACT18 TS - add support for children props
